feat: provide an ability to ignore invalid SSL certificates while usi…
namecheap/ilc pull request #235
Opened 2020-12-18 16:04 UTC by oleh-momot

…ng LDE

2020-12-18 16:49 UTC, StyleT requested changes

2020-12-18 16:49 UTC, StyleT commented on ilc/server/tailor/server-router.spec.js
> +            `<fragment id="${registryConfig.apps['apps'].name}" slot="apps" timeout="${registryConfig.apps.apps.ssr.timeout}" src="${expectedAppsUrl.toString()}" ignore-invalid-ssl="false" primary="t
`ignore-invalid-ssl="false"` counts as true.

2020-12-21 09:45 UTC, oleh-momot commented on ilc/server/tailor/parse-override-config.spec.js
> +const assignIgnoreInvalidSsl = (ssr, protocol = 'http:') => protocol === 'https:'
Added

2020-12-21 09:45 UTC, oleh-momot commented on ilc/server/tailor/server-router.spec.js
> +            `<fragment id="${registryConfig.apps['apps'].name}" slot="apps" timeout="${registryConfig.apps.apps.ssr.timeout}" src="${expectedAppsUrl.toString()}" ignore-invalid-ssl="false" primary="t
Fixed

2020-12-21 09:46 UTC, oleh-momot commented on ilc/server/tailor/parse-override-config.js
> +                        overrideConfig.apps[appName].ssr.ignoreInvalidSsl = true;
Provided a comment to explain it

2020-12-21 09:49 UTC, oleh-momot commented on ilc/server/tailor/parse-override-config.spec.js
> +    describe('ignoring invalid SSL certificates while SSR', () => {
TODO
Add test to check when an app does not have SSR object as a property

2020-12-21 10:18 UTC, StyleT approved these changes

2020-12-21 16:57 UTC, merged