feat: support a few domains (500 template)
namecheap/ilc pull request #283
Opened 2021-04-16 10:00 UTC by nightnei

2021-04-16 14:48 UTC, StyleT requested changes
You have failed tests :(

2021-04-16 14:57 UTC, StyleT commented
Pls write E2E tests for this

2021-04-19 12:24 UTC, nightnei commented
> You have failed tests :(

fixed

2021-04-19 12:24 UTC, nightnei commented
> Pls write E2E tests for this

done

2021-04-19 12:43 UTC, StyleT approved these changes

2021-04-20 07:39 UTC, merged