feat: support a few domains (404)
namecheap/ilc pull request #284
Opened 2021-04-16 10:00 UTC by nightnei

2021-04-16 14:47 UTC, StyleT approved these changes

2021-04-16 14:57 UTC, StyleT commented
Pls write E2E tests for this

2021-04-16 14:57 UTC, StyleT requested changes
Pls write E2E tests for this

2021-04-19 12:30 UTC, nightnei commented
> Pls write E2E tests for this

done

2021-04-19 12:45 UTC, StyleT commented on e2e/spec/404.spec.e2e.ts
> +    I.waitForText(common.text404NotFound, 10, 'body > div#navbar'); // for "127.0.0.1:8233" inside of navbar will be rendered 404 fragment, like in body
I think this test checks nothing... We need to validate that "other" 404 page can be rendered for custom domain.

2021-04-20 07:33 UTC, StyleT approved these changes

2021-04-20 07:40 UTC, merged