chore: added tests for client WrapApp class
namecheap/ilc pull request #302
Opened 2021-05-25 14:55 UTC by ifree92

2021-05-26 05:29 UTC, StyleT requested changes

2021-05-26 05:29 UTC, StyleT commented on ilc/client/WrapApp.spec.js
> +describe('WrapApp', () => {
1. You're missing test cases for unmount (when we have wrapper or app rendered).
2. I would try to write utility function to check state of all callbacks at once. Ex. `expectBallbacksToBe(callbacks, 'mounted')`
3. Separately we need to test the fact that App Wrapper always receives `getCurrentBasePath() = '/'`, unique appId and it's own props while wrapped app receives "own" props from registry.
4. We also need to check that class also works with callbacks provided as array of functions. See `#canonizeCallbacks`

2021-05-26 16:31 UTC, ifree92 commented
@StyleT I have made changes regarding your comments.
Much detalised each case and allocated tests with "arrayed" callbacks as a different tests.

Probably, would be good to group them either:
- by general scenarios: boostrap/mount/unmount wrapper, bootstrap/mount/unmount wrapped app, dynamic render wrapped app after wrapper has been rendered
- or by callbacks approaches, e.g.: normal and "arrayed".

For now leaved as is.

Other moment is about expectations check of arrayed callbacks arguments. I have hardcoded them manually to be able to track the error on exact line. If you prefer to have there an additional abstraction layer - I will do, let me know.

2021-05-26 17:22 UTC, StyleT approved these changes

2021-05-27 15:11 UTC, nightnei approved these changes

2021-05-27 17:11 UTC, merged