docs: add route_configuration_options.md
namecheap/ilc pull request #349
Opened 2022-01-14 14:31 UTC by DammneD

and add assets for it

2022-01-14 14:41 UTC, nightnei commented on docs/routing/route_configuration_options.md
> +# Route configuration options
now our `docs/assets` directory looks like a dump) let's create subdirectory `routes` and relocate all related assets

2022-01-14 14:50 UTC, nightnei commented on docs/routing/route_configuration_options.md
> + ![ILC registry domains field](../assets/domain-field.png)
before screenshot add some introduction information
for example - why developers should specify some domain name. in which cases it's necessary and when it's useless. just imagine, that you are explaining someone - what is it and which value has "router domain"

2022-01-14 14:51 UTC, nightnei commented on docs/routing/route_configuration_options.md
> + - Domain name, must be without protocol, etc.
remove it - it's should be written in documentation about "Router domains" page

2022-01-14 14:57 UTC, nightnei commented on docs/routing/route_configuration_options.md
> + ![ILC registry domains field](../assets/domain-field.png)
Unlike previous documentation, this has independent parts. So it should be not hard to create own description (introductional information) for each of them. So do it please for every part of the current doc.

2022-01-14 15:01 UTC, nightnei requested changes
Unlike previous documentation, this has independent parts. So it should be not hard to create own description (introductional information) for each of them. So do it (https://github.com/namecheap/ilc/pull/349#discussion_r784903476) please for every part of the current doc.

2022-01-17 12:18 UTC, StyleT commented
@nightnei @DammneD guys, let's make new pages visible here https://microfrontends.online/

See:
- https://microfrontends.online/CONTRIBUTING/#documentation-website
- https://github.com/namecheap/ilc/blob/master/mkdocs.yml#L21-L56

2022-01-18 07:52 UTC, nightnei approved these changes

2022-01-18 07:53 UTC, merged