docs: add i18n and trailing slash description file
namecheap/ilc pull request #356
Opened 2022-01-26 12:48 UTC by DammneD

2022-01-26 13:29 UTC, StyleT requested changes

2022-01-26 13:29 UTC, StyleT commented on docs/routing/localisation_and_trailing_slash.md
> + ![Trailing slash settings](../assets/routes/trailing-slash-settings.png)
Pls rm, it's excessive here

2022-01-26 13:29 UTC, StyleT commented on docs/routing/localisation_and_trailing_slash.md
> +![i18n routing strategy](../assets/routes/i18n-settings.png)
Pls rm, it's excessive here

2022-01-26 13:36 UTC, StyleT approved these changes

2022-02-04 18:11 UTC, bandantonio requested changes

2022-02-04 18:11 UTC, bandantonio commented on docs/routing/localisation_and_trailing_slash.md
> +The decision to use a trailing slash or not is more a personal preference than actual necessity, except for some special cases. In any case we provide the ability to control this.
```suggestion
ILC allows you to manage cases with a trailing slash, but the decision to use it is at your discretion, considering personal preference and special cases you may have.
```

2022-02-04 18:11 UTC, bandantonio commented on docs/routing/localisation_and_trailing_slash.md
> +This menu has 3 options:
```suggestion
To manage trailing slash behavior, there are the following options:
```

2022-02-04 18:11 UTC, bandantonio commented on docs/routing/localisation_and_trailing_slash.md
> + 3. **Redirect to trailing slash** - Adds a slash to the end of the URL if it wasn't there.
```suggestion
1. **Do nothing** - No effect at URLs.
1. **Redirect to non-trailing slash** - Remove trailing slash at the end of URLs, if present.
1. **Redirect to trailing slash** - Add trailing slash to the end of URLs, if not present.
```

2022-02-04 18:11 UTC, bandantonio commented on mkdocs.yml
> +      - i18n & trailing slash: docs/routing/localisation_and_trailing_slash.md
```suggestion
      - i18n & trailing slash: docs/routing/localization_and_trailing_slash.md
```

Please rename the markdown file accordingly.

2022-02-07 11:27 UTC, bandantonio approved these changes

2022-02-07 11:46 UTC, nightnei approved these changes

2022-02-07 12:00 UTC, merged