docs: fully revised contribution guide
namecheap/ilc pull request #376
Opened 2022-03-14 11:12 UTC by bandantonio

2022-03-14 12:24 UTC, yehor-manzhula approved these changes

2022-03-28 08:22 UTC, b1ff requested changes

2022-03-28 08:22 UTC, b1ff commented on CONTRIBUTING.md
> +1. (_For internal employees only_): Clone the [ilc.internal](https://git.namecheap.net/projects/RND/repos/ilc.internal/browse) repository
please remove this point, it exposes internal infrastructure

2022-03-28 08:52 UTC, b1ff approved these changes

2022-03-28 08:55 UTC, merged