Fix broken anchors links
namecheap/ilc pull request #427
Opened 2022-06-21 15:46 UTC by yehor-manzhula

2022-06-21 16:24 UTC, b1ff requested changes

2022-06-21 16:24 UTC, b1ff commented on ilc/client/TransitionManager/TransitionManager.js
>      #transactionBlockerExists = (blockerId) => {
probably methods also require renaming

2022-06-21 16:24 UTC, b1ff commented on ilc/client/TransitionManager/TransitionManager.js
> +        .onDestroy(() => observer.disconnect());
observer?.disconnect() ?

2022-06-22 07:26 UTC, yehor-manzhula commented on ilc/client/TransitionManager/TransitionManager.js
>      #transactionBlockerExists = (blockerId) => {
renamed

2022-06-22 07:27 UTC, yehor-manzhula commented on ilc/client/TransitionManager/TransitionManager.js
> +        .onDestroy(() => observer.disconnect());
added condition

2022-06-22 07:41 UTC, b1ff approved these changes

2022-06-29 13:23 UTC, blackrabbit99 commented on ilc/client/TransitionManager/TransitionBlocker.js
> +export default class TransitionBlocker {
What is the responsibility of its class ?

2022-06-29 13:31 UTC, blackrabbit99 commented on ilc/client/TransitionManager/TransitionManager.js
> +            }
else window.scroll(0, 0); ?

2022-06-29 13:33 UTC, blackrabbit99 commented on ilc/client/TransitionManager/TransitionManager.js
>      if (defaultInstance === null) {
can we rename it to understand `defaultInstance` of what ?

2022-06-30 08:01 UTC, yehor-manzhula commented on ilc/client/TransitionManager/TransitionManager.js
> +                document.body.setAttribute('name', window.location.hash.slice(1));
As I can see from the tests, it is used for testing purposes to check if page transition has happened.

2022-07-01 07:52 UTC, blackrabbit99 approved these changes

2022-07-01 08:53 UTC, merged